spring.application.name=wish_list
# Altera a estrutura da tabela caso a entidade tenha mudança.
spring.jpa.hibernete.ddl-auto=update

# Acessa ao banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/task_master_pro

# Usuário do banco de dados
spring.datasource.username=postgres

# Senha do banco de dados
spring.datasource.password=